/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hitseq.gui;

import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.ListModel;
import java.io.File;
import java.io.IOException;
import java.io.PrintStream;
import java.io.OutputStream;
import java.util.Iterator;
import java.util.HashSet;
import java.util.List;
import javax.swing.SwingUtilities;

class CustumizedFileFilter extends javax.swing.filechooser.FileFilter{
    String[] extension;
    String description;
    CustumizedFileFilter(String[] extension, String description){
        this.extension=extension;
        this.description=description;
    }
    
    @Override
    public boolean accept(File file){
        boolean fit=false;
        if(file.isDirectory())
            fit=true;
        else{
            for(String ext : extension){
                if(file.getAbsolutePath().toLowerCase().endsWith(ext)){
                    fit=true;
                    break;
                }
            }
        }
        return fit;
    }
    
    @Override
    public String getDescription(){
        String extensionString="";
        for(String ext : extension){
            if(! extensionString.equals(""))
                extensionString+=";";
            extensionString+="*"+ext;
        }
        return description + " (" + extensionString + ")";
    }
}

/**
 *
 * @author Chih-sung
 */
public class GraphicUserInterface extends javax.swing.JFrame {
    private CommandRunner runner;
    private ParameterSet parameters;
    final private PrintStream stderr=System.err;
    
    /**
     * Creates new form GraphicUserInterface
     */
    public GraphicUserInterface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupCountAnnotationType = new javax.swing.ButtonGroup();
        buttonGroupCountRemovePCR = new javax.swing.ButtonGroup();
        buttonGroupCountStrand = new javax.swing.ButtonGroup();
        buttonGroupCountNHTag = new javax.swing.ButtonGroup();
        jDialogCountProgress = new javax.swing.JDialog();
        jButtonCountSaveLog = new javax.swing.JButton();
        jProgressBarCount = new javax.swing.JProgressBar();
        jLabel5 = new javax.swing.JLabel();
        jButtonCountSave = new javax.swing.JButton();
        jButtonCountCancel = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaLog = new javax.swing.JTextArea();
        jFileChooser = new javax.swing.JFileChooser();
        jFileSaver = new javax.swing.JFileChooser();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelUniqReads = new javax.swing.JPanel();
        jPanelReadCount = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jTextFieldCountAnnot = new javax.swing.JTextField();
        jButtonCountChooseAnnot = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPaneCountBAMFiles = new javax.swing.JScrollPane();
        jListCountBAMFiles = new javax.swing.JList();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jRadioButton9 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        jButtonRunCount = new javax.swing.JButton();
        jPanelJuncCount = new javax.swing.JPanel();

        jDialogCountProgress.setTitle("Read Counting ongoing");
        jDialogCountProgress.setBounds(new java.awt.Rectangle(200, 200, 0, 0));
        jDialogCountProgress.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jDialogCountProgress.setMaximumSize(new java.awt.Dimension(400, 235));
        jDialogCountProgress.setMinimumSize(new java.awt.Dimension(400, 235));
        jDialogCountProgress.setResizable(false);

        jButtonCountSaveLog.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jButtonCountSaveLog.setText("Save Log As");
        jButtonCountSaveLog.setEnabled(false);
        jButtonCountSaveLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCountSaveLogActionPerformed(evt);
            }
        });

        jProgressBarCount.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jProgressBarCount.setStringPainted(true);

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel5.setText("Progress");

        jButtonCountSave.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jButtonCountSave.setText("Save As");
        jButtonCountSave.setEnabled(false);
        jButtonCountSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCountSaveActionPerformed(evt);
            }
        });

        jButtonCountCancel.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jButtonCountCancel.setText("Cancel");
        jButtonCountCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCountCancelActionPerformed(evt);
            }
        });

        jTextAreaLog.setColumns(20);
        jTextAreaLog.setFont(new java.awt.Font("Monospaced", 0, 10)); // NOI18N
        jTextAreaLog.setRows(5);
        jScrollPane1.setViewportView(jTextAreaLog);

        javax.swing.GroupLayout jDialogCountProgressLayout = new javax.swing.GroupLayout(jDialogCountProgress.getContentPane());
        jDialogCountProgress.getContentPane().setLayout(jDialogCountProgressLayout);
        jDialogCountProgressLayout.setHorizontalGroup(
            jDialogCountProgressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogCountProgressLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialogCountProgressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jProgressBarCount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(jDialogCountProgressLayout.createSequentialGroup()
                        .addGroup(jDialogCountProgressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jDialogCountProgressLayout.createSequentialGroup()
                                .addComponent(jButtonCountSave)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonCountSaveLog)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonCountCancel)))
                        .addGap(0, 97, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jDialogCountProgressLayout.setVerticalGroup(
            jDialogCountProgressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogCountProgressLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jProgressBarCount, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialogCountProgressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCountSave)
                    .addComponent(jButtonCountCancel)
                    .addComponent(jButtonCountSaveLog))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jFileChooser.setDialogTitle("Select the Annotation file");

        jFileSaver.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(100, 100, 0, 0));
        setResizable(false);

        jTabbedPane1.setEnabled(false);
        jTabbedPane1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        jPanelUniqReads.setEnabled(false);

        javax.swing.GroupLayout jPanelUniqReadsLayout = new javax.swing.GroupLayout(jPanelUniqReads);
        jPanelUniqReads.setLayout(jPanelUniqReadsLayout);
        jPanelUniqReadsLayout.setHorizontalGroup(
            jPanelUniqReadsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 531, Short.MAX_VALUE)
        );
        jPanelUniqReadsLayout.setVerticalGroup(
            jPanelUniqReadsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 629, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Extract Unique Reads", jPanelUniqReads);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Choose Annotations", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 14))); // NOI18N
        jPanel4.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        jTextFieldCountAnnot.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jTextFieldCountAnnot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCountAnnotActionPerformed(evt);
            }
        });

        jButtonCountChooseAnnot.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jButtonCountChooseAnnot.setText("Choose");
        jButtonCountChooseAnnot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCountChooseAnnotActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        jLabel1.setText("Annotation Type");

        buttonGroupCountAnnotationType.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jRadioButton1.setText("GTF");

        buttonGroupCountAnnotationType.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jRadioButton2.setText("STRUC");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        buttonGroupCountAnnotationType.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jRadioButton3.setText("BED");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jRadioButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton3))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jTextFieldCountAnnot, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCountChooseAnnot)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCountAnnot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCountChooseAnnot))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3)))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Choose BAM/SAM Files", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 14))); // NOI18N
        jPanel1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        jListCountBAMFiles.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jScrollPaneCountBAMFiles.setViewportView(jListCountBAMFiles);

        jButton3.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jButton3.setText("Choose");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jButton5.setText("Delete");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneCountBAMFiles)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jButton3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton5)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(132, 132, 132)
                        .addComponent(jButton5))
                    .addComponent(jScrollPaneCountBAMFiles))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Other Parameters", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 14))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel2.setText("Remove PCR artifact?");

        buttonGroupCountRemovePCR.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jRadioButton4.setText("Yes");

        buttonGroupCountRemovePCR.add(jRadioButton5);
        jRadioButton5.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jRadioButton5.setSelected(true);
        jRadioButton5.setText("No");

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel3.setText("Strand specific?");

        buttonGroupCountStrand.add(jRadioButton6);
        jRadioButton6.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jRadioButton6.setSelected(true);
        jRadioButton6.setText("No");

        buttonGroupCountStrand.add(jRadioButton7);
        jRadioButton7.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jRadioButton7.setText("Same strand");

        buttonGroupCountStrand.add(jRadioButton8);
        jRadioButton8.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jRadioButton8.setText("Opposite strand");

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel4.setText("Use NH tag?");

        buttonGroupCountNHTag.add(jRadioButton9);
        jRadioButton9.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jRadioButton9.setText("Yes");

        buttonGroupCountNHTag.add(jRadioButton10);
        jRadioButton10.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jRadioButton10.setSelected(true);
        jRadioButton10.setText("No");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jRadioButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton5))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton6)
                            .addComponent(jRadioButton9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton10)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jRadioButton7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton8)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jRadioButton4)
                    .addComponent(jRadioButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jRadioButton6)
                    .addComponent(jRadioButton7)
                    .addComponent(jRadioButton8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jRadioButton9)
                    .addComponent(jRadioButton10))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonRunCount.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jButtonRunCount.setText("RUN");
        jButtonRunCount.setEnabled(false);
        jButtonRunCount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRunCountActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelReadCountLayout = new javax.swing.GroupLayout(jPanelReadCount);
        jPanelReadCount.setLayout(jPanelReadCountLayout);
        jPanelReadCountLayout.setHorizontalGroup(
            jPanelReadCountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelReadCountLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelReadCountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonRunCount)
                    .addGroup(jPanelReadCountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelReadCountLayout.setVerticalGroup(
            jPanelReadCountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelReadCountLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonRunCount)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Read Counting", jPanelReadCount);

        jPanelJuncCount.setEnabled(false);

        javax.swing.GroupLayout jPanelJuncCountLayout = new javax.swing.GroupLayout(jPanelJuncCount);
        jPanelJuncCount.setLayout(jPanelJuncCountLayout);
        jPanelJuncCountLayout.setHorizontalGroup(
            jPanelJuncCountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 531, Short.MAX_VALUE)
        );
        jPanelJuncCountLayout.setVerticalGroup(
            jPanelJuncCountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 629, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Junction Counting", jPanelJuncCount);

        jTabbedPane1.setSelectedIndex(1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Read Counting");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldCountAnnotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCountAnnotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCountAnnotActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    /**
     * Select annotation file
     * @param evt 
     */
    private void jButtonCountChooseAnnotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCountChooseAnnotActionPerformed
        jFileChooser.setMultiSelectionEnabled(false);
        jFileChooser.setDialogTitle("Select the Annotation File");
        jFileChooser.resetChoosableFileFilters();
        jFileChooser.setFileFilter(new CustumizedFileFilter(new String[]{".gtf",".struc",".bed"}, "Supported annotation documents"));
        
        int returnVal=jFileChooser.showOpenDialog(this);
        if(returnVal == JFileChooser.APPROVE_OPTION){
            File file = jFileChooser.getSelectedFile();
            String path=file.getAbsolutePath();
            jTextFieldCountAnnot.setText(path);
            jTextFieldCountAnnot.setEditable(false);
            
            if(path.toLowerCase().endsWith(".gtf")){
                jRadioButton1.setSelected(true);
            } else if(path.toLowerCase().endsWith(".struc")){
                jRadioButton2.setSelected(true);
            } else if(path.toLowerCase().endsWith(".bed")){
                jRadioButton3.setSelected(true);
            }
        }
        
        if(! jTextFieldCountAnnot.getText().isEmpty() && jListCountBAMFiles.getModel().getSize()>0)
            jButtonRunCount.setEnabled(true);
    }//GEN-LAST:event_jButtonCountChooseAnnotActionPerformed

    /**
     * Select mapping files
     * @param evt 
     */
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jFileChooser.setMultiSelectionEnabled(true);
        jFileChooser.setDialogTitle("Select the SAM/BAM Files");
        jFileChooser.resetChoosableFileFilters();
        jFileChooser.setFileFilter(new CustumizedFileFilter(new String[]{".sam",".bam"}, "Read mapping files"));
        
        int returnVal=jFileChooser.showOpenDialog(this);
        if(returnVal == JFileChooser.APPROVE_OPTION){
            File[] files = jFileChooser.getSelectedFiles();
            
            HashSet<String> filesInList=new HashSet<>();
            ListModel lm=jListCountBAMFiles.getModel();
            if(lm.getSize()>0)
                for(int i=0; i<lm.getSize(); i++)
                    filesInList.add(lm.getElementAt(i).toString());
            for(File file : files)
                filesInList.add(file.getAbsolutePath());
            
            DefaultListModel dlm=new DefaultListModel();
            Iterator<String> iterator=filesInList.iterator();
            while(iterator.hasNext())
                dlm.addElement(iterator.next());
            
            jListCountBAMFiles.setModel(dlm);
        }
        
        if(! jTextFieldCountAnnot.getText().isEmpty() && jListCountBAMFiles.getModel().getSize()>0)
            jButtonRunCount.setEnabled(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * Delete selected mapping files from the list
     * @param evt 
     */
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if(jListCountBAMFiles.getSelectedValuesList().size()>0){
            HashSet<String> files=new HashSet<>();
            ListModel lm=jListCountBAMFiles.getModel();
            for(int i=0; i<lm.getSize(); i++)
                files.add(lm.getElementAt(i).toString());
            List selectedList=jListCountBAMFiles.getSelectedValuesList();
            for(Object selected : selectedList)
                files.remove(selected.toString());
            
            DefaultListModel dlm=new DefaultListModel();
            Iterator<String> iterator=files.iterator();
            while(iterator.hasNext())
                dlm.addElement(iterator.next());
            
            jListCountBAMFiles.setModel(dlm);
        }
        
        if(jListCountBAMFiles.getModel().getSize()==0)
            jButtonRunCount.setEnabled(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * Run read counting
     * @param evt 
     */
    private void jButtonRunCountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRunCountActionPerformed
        jProgressBarCount.setValue(0);
        jDialogCountProgress.setVisible(true);
        this.setEnabled(false);
        redirectSystemStreamsToLog();
        jTextAreaLog.setText("");
        
        // set parameter set
        parameters=new ParameterSet();
        parameters.setAnnotFile(new File(jTextFieldCountAnnot.getText()));
        ListModel lm=jListCountBAMFiles.getModel();
        for(int i=0; i<lm.getSize(); i++)
            parameters.addMappingFile(new File(lm.getElementAt(i).toString()));
        parameters.setConsiderNHTag(jRadioButton9.isSelected());
        parameters.setReadCollapse(jRadioButton4.isSelected());
        int strand=0;
        if(jRadioButton7.isSelected())
            strand=1;
        else if(jRadioButton8.isSelected())
            strand=-1;
        parameters.setStrandness(strand);
        
        // run program
        runner=new CommandRunner("count", parameters, jProgressBarCount, new javax.swing.JButton[]{ jButtonCountSave, jButtonCountSaveLog}, jButtonCountCancel);
        runner.start();
    }//GEN-LAST:event_jButtonRunCountActionPerformed

    /**
     * Cancel read counting
     * @param evt 
     */
    private void jButtonCountCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCountCancelActionPerformed
        System.setErr(stderr);
        runner.interrupt();
        jDialogCountProgress.setVisible(false);
        this.setEnabled(true);
        this.requestFocus();
    }//GEN-LAST:event_jButtonCountCancelActionPerformed

    /**
     * Save the counting result
     * @param evt 
     */
    private void jButtonCountSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCountSaveActionPerformed
        System.setErr(stderr);
        jFileSaver.setMultiSelectionEnabled(false);
        jFileSaver.setDialogTitle("Save the Result As");
        jFileSaver.cancelSelection();
        
        int returnVal=jFileSaver.showSaveDialog(this);
        if(returnVal == JFileChooser.APPROVE_OPTION){
            File file = jFileSaver.getSelectedFile();
            PrintStream stdout=System.out;
            try (OutputStream out = redirectSystemOutputStreamsToFile(file)) {
                runner.generateOutputString();
                System.setOut(stdout);
                out.close();
            } catch (Exception e) {
                System.err.println("Cannot open or write the selected result file.");
                System.err.println(e);
            }
        }
    }//GEN-LAST:event_jButtonCountSaveActionPerformed

    /**
     * Save the log for read counting
     * @param evt 
     */
    private void jButtonCountSaveLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCountSaveLogActionPerformed
        System.setErr(stderr);
        jFileSaver.setMultiSelectionEnabled(false);
        jFileSaver.setDialogTitle("Save the Log As");
        jFileSaver.cancelSelection();
        
        int returnVal=jFileSaver.showSaveDialog(this);
        if(returnVal == JFileChooser.APPROVE_OPTION){
            File file = jFileSaver.getSelectedFile();
            PrintStream stdout=System.out;
            try(OutputStream out = redirectSystemOutputStreamsToFile(file)){
                String text=jTextAreaLog.getText();
                System.out.print(text);
                System.setOut(stdout);
                out.close();
            } catch (IOException e){
                System.err.println("Cannot open or write the selected log file.");
                System.err.println(e);
            }
        }
    }//GEN-LAST:event_jButtonCountSaveLogActionPerformed

    
    private void updateTextAreaLog(final String text){
        SwingUtilities.invokeLater(new Runnable(){
            @Override
            public void run(){
                jTextAreaLog.append(text);
            }
        });
    }
    
    private void redirectSystemStreamsToLog(){
        OutputStream out = new OutputStream(){
            @Override
            public void write(int b) throws IOException{
                updateTextAreaLog(String.valueOf((char) b));
            }
            @Override
            public void write(byte[] b, int off, int len) throws IOException{
                updateTextAreaLog(new String(b,off,len));
            }
            @Override
            public void write(byte[] b) throws IOException{
                write(b, 0, b.length);
            }
        };
        
        System.setErr(new PrintStream(out, true));
    }
    
    private OutputStream redirectSystemOutputStreamsToFile(File file){
        try{
            if(file.exists())
                file.delete();
            file.createNewFile();
            
            OutputStream out = new java.io.FileOutputStream(file);
            System.setOut(new PrintStream(out, true));
            return out;
        } catch(Exception e){
            System.err.println(e);
            return null;
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GraphicUserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new GraphicUserInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupCountAnnotationType;
    private javax.swing.ButtonGroup buttonGroupCountNHTag;
    private javax.swing.ButtonGroup buttonGroupCountRemovePCR;
    private javax.swing.ButtonGroup buttonGroupCountStrand;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButtonCountCancel;
    private javax.swing.JButton jButtonCountChooseAnnot;
    private javax.swing.JButton jButtonCountSave;
    private javax.swing.JButton jButtonCountSaveLog;
    private javax.swing.JButton jButtonRunCount;
    private javax.swing.JDialog jDialogCountProgress;
    private javax.swing.JFileChooser jFileChooser;
    private javax.swing.JFileChooser jFileSaver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JList jListCountBAMFiles;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelJuncCount;
    private javax.swing.JPanel jPanelReadCount;
    private javax.swing.JPanel jPanelUniqReads;
    private javax.swing.JProgressBar jProgressBarCount;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPaneCountBAMFiles;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextAreaLog;
    private javax.swing.JTextField jTextFieldCountAnnot;
    // End of variables declaration//GEN-END:variables
}
